apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-demo1
  labels:
    app: tracing-demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-demo1
  template:
    metadata:
      labels:
        app: tracing-demo1
    spec:
      containers:
      - name: tracing-demo-container1
        image: leonardobonacci/tracing-one-demo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-demo1
spec:
  selector:
    app: tracing-demo1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-demo2
  labels:
    app: tracing-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-demo2
  template:
    metadata:
      labels:
        app: tracing-demo2
    spec:
      containers:
      - name: tracing-demo-container2
        image: leonardobonacci/tracing-two-demo:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-demo2
spec:
  selector:
    app: tracing-demo2
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: NodePort
